"""
report_generator.py — Generate clinical and patient-friendly reports from analysis data.

Produces formatted Markdown reports suitable for download as PDF or sharing.
"""
import json
from datetime import datetime
from typing import Optional


def generate_clinical_report(
    analysis_result: dict,
    variant_info: Optional[dict] = None,
    include_tool_log: bool = True
) -> str:
    """
    Generate a formatted clinical-style report from the analysis.

    Args:
        analysis_result: Result from GemmaAgent.analyze_variant()
        variant_info: Optional parsed variant dictionary
        include_tool_log: Whether to include the tool call log

    Returns:
        Markdown-formatted clinical report string.
    """
    now = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    query = analysis_result.get("query", "Unknown variant")
    analysis = analysis_result.get("analysis", "No analysis available.")
    tool_calls = analysis_result.get("tool_calls", [])
    turns = analysis_result.get("turns_used", 0)
    elapsed = analysis_result.get("elapsed_seconds", 0)
    model = analysis_result.get("model", "gemma-4-31b-it")

    report_lines = [
        "# GeneSight — Genetic Variant Analysis Report",
        "",
        "---",
        "",
        f"**Generated:** {now}",
        f"**Query:** {query}",
        f"**Model:** {model}",
        f"**Analysis Duration:** {elapsed}s ({turns} agentic turns)",
        "",
    ]

    # Variant info if available
    if variant_info:
        report_lines.extend([
            "## Variant Information",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
        ])
        for key, val in variant_info.items():
            if val and key != "raw_input":
                report_lines.append(f"| {key.replace('_', ' ').title()} | {val} |")
        report_lines.append("")

    # Main analysis
    report_lines.extend([
        "## Clinical Analysis",
        "",
        analysis,
        "",
    ])

    # Tool call evidence trail
    if include_tool_log and tool_calls:
        report_lines.extend([
            "---",
            "",
            "## Evidence Trail (Tool Calls)",
            "",
            "The following databases were queried during this analysis:",
            "",
        ])
        for i, tc in enumerate(tool_calls, 1):
            tool_name = tc["tool"].replace("tool_", "").replace("_", " ").title()
            args_str = ", ".join(f"{k}={v}" for k, v in tc.get("args", {}).items())
            report_lines.extend([
                f"### {i}. {tool_name}",
                f"**Arguments:** `{args_str}`",
                "",
                "```json",
                tc.get("result_preview", "No data"),
                "```",
                "",
            ])

    # Disclaimer
    report_lines.extend([
        "---",
        "",
        "## ⚠️ Disclaimer",
        "",
        "> **This report is generated by GeneSight, an AI-powered research and educational tool.**",
        "> It is NOT a substitute for professional genetic counseling or clinical diagnosis.",
        "> All findings should be reviewed by a qualified healthcare professional before any",
        "> clinical decisions are made. GeneSight uses the Gemma 4 model and publicly available",
        "> databases (ClinVar, UniProt, PubMed) which may not reflect the most current data.",
        "",
        "---",
        "",
        "*Report generated by GeneSight — Powered by Gemma 4*",
    ])

    return "\n".join(report_lines)


def generate_report_summary_card(analysis_result: dict) -> dict:
    """
    Extract key summary data for UI display cards.

    Args:
        analysis_result: Result from GemmaAgent.analyze_variant()

    Returns:
        Dictionary with key summary fields for UI cards.
    """
    analysis = analysis_result.get("analysis", "")
    tool_calls = analysis_result.get("tool_calls", [])

    # Try to extract classification from analysis text
    classification = "Unknown"
    confidence = "N/A"
    for line in analysis.split("\n"):
        line_lower = line.lower()
        if "pathogenic" in line_lower and "classif" in line_lower:
            if "likely pathogenic" in line_lower:
                classification = "Likely Pathogenic"
            elif "likely benign" in line_lower:
                classification = "Likely Benign"
            elif "benign" in line_lower:
                classification = "Benign"
            elif "pathogenic" in line_lower:
                classification = "Pathogenic"
            break
        elif "uncertain" in line_lower or "vus" in line_lower:
            classification = "VUS"
            break

    # Extract databases queried
    databases_used = list(set(
        tc["tool"].replace("tool_", "").replace("_", " ").title()
        for tc in tool_calls
    ))

    # Count papers found
    papers_found = 0
    for tc in tool_calls:
        if tc["tool"] == "tool_search_pubmed":
            try:
                result_data = json.loads(tc.get("result_preview", "{}").rstrip("..."))
                papers_found = result_data.get("total_results", 0)
            except (json.JSONDecodeError, AttributeError):
                pass

    return {
        "classification": classification,
        "confidence": confidence,
        "databases_queried": databases_used,
        "num_databases": len(databases_used),
        "papers_found": papers_found,
        "turns_used": analysis_result.get("turns_used", 0),
        "elapsed": analysis_result.get("elapsed_seconds", 0),
    }
